### PR TITLE
support service owner filtering

### PR DESCRIPTION
**Pull request by ala85**
I would like to support the ability to filter nodes based on service owner. An optional field named "owner" can be defined in the metadata object and be used when highlighting nodes during search, so that you can search and match for both node names and owner (aka team name), if provided.

### CODE REVIEW

**Comment by jrsquared** [comment]
Looks great. This should definitely be pluggable at some point, but for now, this is great.

**Comment by jrsquared** [comment]
This is live in v4.7.3

**Comment by ala85** [comment]
Thanks again. To get it as part of vizceral-react should I open a PR there or will you update it to 4.7.3 here? https://github.com/Netflix/vizceral-react/blob/master/package.json

**Comment by jrsquared** [comment]
It's in vizceral-react@4.6.5

**Comment by ala85** [comment]
Awesome stuff

**Pull request merged**
