### PR TITLE
Extend color control when node is selected

### PR DESCRIPTION
**Pull request by fervanrijswijk**
As reported here: https://github.com/Netflix/vizceral/issues/102

Having a white background I found it hard to use a color which holds up when the node is selected. By default the color of the node will brightened.
With this PR the user will have the ability the provide a color for highlighted node;

```
this.vizceral.updateStyles({
  colorText: 'rgb(255, 255, 255)', // Text in label
  colorTraffic: {
    normal: 'rgb(0, 75, 111)', // Normal node border, label fill, Transaction fill
    warning: 'rgb(268, 185, 73)',
    danger: 'rgb(184, 36, 36)',
    customClass: '#cccccc'
  },
  colorTrafficHighlighted: {
    customClass: '#333333'
  },
  colorLabelBorder: 'rgba(255, 255, 255, 0)', // Label border
  colorLabelText: 'rgb(255, 255, 255)', // Label text
  colorDonutInternalColor: 'rgb(245, 245, 245)', // Node fill
  colorConnectionLine: 'rgba(20, 20, 20, 0.4)' // Relation line
});

### CODE REVIEW

**Comment by vshamgin** [comment]
@fervanrijswijk You should create an issue, so your PR will have the reference.

**Comment by fervanrijswijk** [comment]
@vshamgin Thanks. I hope I've done it the right way now :-)

**Comment by jrsquared** [comment]
Very nice, I like this.

**Comment by jrsquared** [comment]
Fixes #102

**Pull request merged**
