### PR TITLE
To change color of a node, based on class #98

### PR DESCRIPTION
**Pull request by vshamgin**
Issue: https://github.com/Netflix/vizceral/issues/98

To be able to change color of a node, based on "class" property value in node's json data, like:

```
        {
          "name": "ShapeUser",
          "node_type": "user",
          "renderer": "focusedChild",
          "class": "danger"
        }

```
Screenshot:
https://www.dropbox.com/sh/bvfwaw3p2r7j2by/AACAkrxXZK76982lz4s-JMyra?dl=0&preview=node_health.png

### CODE REVIEW

**Comment by vshamgin** [comment]
If node class is set known values (default, normal, warning, danger), Shape class will pick the corresponding RGB value:
```
      colorNodeHealth: {
        default: 'rgb(120, 120, 120)',
        normal: 'rgb(120, 120, 120)',
        warning: 'rgb(268, 185, 73)',
        danger: 'rgb(255, 53, 53)'
      }
```
If class is missing or unknown, the default color will be used:
```
    this.shapesStyles = {
      colorShapeDefault: 'rgb(120, 120, 120)'
    };
```

**Comment by clusteratlas** [comment]
Love this.

**Comment by jrsquared** [comment]
This is great! My only comment would be to synchronize the naming. In the traffic graph JSON it's `class`, in the colors it's `colorNodeHealth`. Maybe since the colors may or may not be used for health, switching to `colorNodeClass` makes more sense.

**Comment by vshamgin** [comment]
@jrsquared  Per given comments:
1. Node status could be defined as "nodeStatus":
```
        {
          "name": "ShapeService",
           ..
          "nodeStatus": "normal"
      }
```
in globalStyles it corresponds with:

```
      colorNodeStatus: {
        default: 'rgb(120, 120, 120)',
        normal: 'rgb(127, 255, 0)',
        warning: 'rgb(268, 185, 73)',
        danger: 'rgb(255, 53, 53)'
      }
```
If "nodeStatus" is not set or set no an unknown value, the node will be rendered with it's default style.

2. Shapes classes are optimized by moving some functions (_createOuterBorder, _createMaterial) to their parent class - ShapeParent

**Comment by fervanrijswijk** [comment]
Isn't this already a feature of Vizceral? Just put the classname of the node in 'colorTraffic' and than update styles:

```
this.vizceral.updateStyles({
  colorTraffic: {
    normal: 'rgb(0, 75, 111)', // Normal node border, label fill, Transaction fill
    warning: 'rgb(268, 185, 73)',
    danger: 'rgb(184, 36, 36)',
    customClass: '#cccccc'
  },
});

**Comment by vshamgin** [comment]
@fervanrijswijk My "feature" is a data-driven node status and has nothing to do with just hacking color styles in globalStyles.
Also, as @jrsquared mentioned previously, names should be consistent. Node-related styles should not be placed traffic styles and vice versa.

**Pull request merged**
